---
- name: Reboot the server
  hosts: your_target_host
  become: yes

  tasks:
    - name: Reboot server
      reboot:
        msg: "Rebooting for kernel update"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime